<x-lareon::admin-layout>
    @section('title', __('logs'))
    @section('description', __("a log file is a record of events, activities, or errors generated by the application or server for monitoring and debugging purposes"))
    @section('header.start')
        <form action="" method="get" id="changeLog">
            <x-lareon::editor.input-select :value="request()->input('name' ,'laravel')" wrapperClass="flex gap-3 items-center" :label="__('files')" name="name" onchange="this.form.submit()" aria-label="{{__('logs')}}">
                @foreach($logs ?? [] as $file)
                    <option value="{{$file}}" >{{$file}}</option>
                @endforeach
            </x-lareon::editor.input-select>
        </form>
    @endsection

    @section('header.end')
        @can('admin.setting.log.clear')
            <form action="{{route('admin.settings.logs.clear')}}" method="POST">
                @csrf
                @method('patch')
                <input type="hidden" class="hidden" name="name" value="{{$name}}">
                <x-lareon::buttons.nav color="delete" size="xs">
                    {{__('clear')}}
                </x-lareon::buttons.nav>
            </form>
        @endcan
        @can('admin.setting.log.delete')
            <form action="{{route('admin.settings.logs.destroy')}}" method="POST">
                @csrf
                @method('delete')
                <input type="hidden" class="hidden" name="name" value="{{$name}}">
                <x-lareon::buttons.nav color="delete" variant="outline" size="xs">
                    {{__('delete')}}
                </x-lareon::buttons.nav>
            </form>
        @endcan
    @endsection

    <section class="mb-6" x-data="{ dark: true, wrap: true }">
        <div class="grid items-center grid-cols-2 mb-2">
            <div>
                <h3>
                    {{$name}}
                </h3>
            </div>
           <div class="flex items-center justify-end">
               <button type="button" @click="dark = !dark" class="px-3 py-1 rounded border text-sm">
                   <span x-text="dark ? '☀️ Light' : '🌙 Dark'"></span>
               </button>
               <button type="button" @click="wrap = !wrap" class="px-3 py-1 rounded border text-sm">
                   <span x-text="wrap ? '➡️ unwrap' : '↩️  wrap'"></span>
               </button>
           </div>
        </div>
        <div dir="ltr" class="font-semibold p-6 rounded-lg w-full max-h-screen overflow-auto transition-colors duration-300"
             :class="dark ? 'bg-zinc-900 text-gray-300'    : 'bg-slate-50 text-gray-900 border'">
            <pre :class="wrap ? 'whitespace-pre-wrap'    : ''">{!! $content !!}</pre>
        </div>

    </section>

</x-lareon::admin-layout>
